{"type":"getPostByPath","data":{"title":"unlimited-errors","date":"2022-06-23T00:00:00.000Z","description":"","categories":[{"name":"技术","_id":"clanavjfy000dadoqcytmejju"},{"name":"Lua","_id":"clanavjgj0018adoq9r508bvu"}],"tags":[{"name":"Dice","_id":"clanavjfx000cadoq38hoan0h"}],"content":"<details class=\"note \"><summary><p>secondary</p>\n</summary>\n<p><strong>目前正在努力ing…</strong><br>利用 <code>error()</code>与 <code>pcall()</code>进行lua自定义报错</p>\n\n</details>\n\n<h2 id=\"前言\"><a href=\"#前言\" class=\"headerlink\" title=\"前言\"></a>前言</h2><blockquote>\n<p>使用《署名—非商业性使用—相同方式共享4.0 协议国际版》（CC BY-NC-SA 4.0）进行授权<span class=\"exturl\" data-url=\"aHR0cHM6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL2xpY2Vuc2VzL2J5LW5jLXNhLzQuMC9sZWdhbGNvZGUuemgtSGFucw==\">https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.zh-Hans<i class=\"fa fa-external-link-alt\"></i></span><br>作者：简律纯<br>联系方式：qq:A2C29K9<br>更新日期：2022/5/28</p>\n</blockquote>\n<div class=\"note warning\"><p><strong>WARNING ⚠️</strong><br>本帖是作为利用basicFunction自带的chat指令并结合修改chat指令内tryCatch部分的函数名来进行报错排查的示例帖。</p>\n<blockquote>\n<p>简言之让报错更好看一点，更容易理解一点。</p>\n</blockquote>\n</div>\n\n<p>taboo前些日子（好久了）评论了<span class=\"exturl\" data-url=\"aHR0cHM6Ly9mb3J1bS5rb2tvbmEudGVjaC9kLzExNDctemhpLWxpbmctamlhby1iZW4ta3VvLXpoYW4taGFuLXNodS1rdS1jaGkteHUtemhvdS1nZW5n\">basicFunction<i class=\"fa fa-external-link-alt\"></i></span> 的tryCatch函数，他说，</p>\n<blockquote>\n<p>骰娘自检可以安排到行程上了</p>\n</blockquote>\n<p>虽然和写tryCatch的初衷完全不一样，但是返校后在考试过程中突然发现这会是一个很不错的想法，于是单独写一篇帖子介绍它。</p>\n<h2 id=\"开始\"><a href=\"#开始\" class=\"headerlink\" title=\"开始\"></a>开始</h2><h3 id=\"1-准备工作\"><a href=\"#1-准备工作\" class=\"headerlink\" title=\"1. 准备工作\"></a>1. 准备工作</h3><p>首先我们在basicFunction的chat指令函数里的tryCatch部分写上这些代码，图片中的抓取报错函数示例是 <code>read_file()</code>函数，输入的参数是path，文件路径；返回值为文件内容。<br><img src=\"https://dice-forum.s3.ap-northeast-1.amazonaws.com/2022-05-28/1653713607-498189-screenshot-2022-05-28-12-41-00-92.jpg\"><br>这段代码的意思是如果报错信息里有nil这个字符串那返回自定义报错回复内容，否则返回read_file函数的返回内容。</p>\n<h3 id=\"2-第一次测试\"><a href=\"#2-第一次测试\" class=\"headerlink\" title=\"2.第一次测试\"></a>2.第一次测试</h3><p>接着输入 <code>#basicFunction:tryCatch</code>，不带任何参数，它等效于 <code>#basicFunction:read_file</code>接着的确报错了，但是因为 <code>read_file()</code>函数的path参数为空，报错信息中有nil字符串，于是被替换成了预先写好的自定义报错回复内容。<br>接着我使用 <code>#basicFunction:read_file myDiary.txt</code> 查看了此文件，由于这个文件并不存在，于是krypton返回了read_file里写好的自定义回复。<br><img src=\"https://dice-forum.s3.ap-northeast-1.amazonaws.com/2022-05-28/1653713518-807281-74092e56946e00a4.png\"></p>\n<h3 id=\"3-修改\"><a href=\"#3-修改\" class=\"headerlink\" title=\"3.修改\"></a>3.修改</h3><p>那么我们使用 <code>#basicFunction:write_file myDiary.txt [内容]</code>来创建这个文件并且写下点什么<del>烂人诅咒</del><br><img src=\"https://dice-forum.s3.ap-northeast-1.amazonaws.com/2022-05-28/1653713557-476439-432aa460c37a0fe9.png\"></p>\n<h3 id=\"4-第二次测试\"><a href=\"#4-第二次测试\" class=\"headerlink\" title=\"4.第二次测试\"></a>4.第二次测试</h3><p>已经写好了此文件，我们再用 <code>#basicFunction:read_file myDiary.txt</code>查看一下，来确保有此文件并且写入了内容。<br><img src=\"https://dice-forum.s3.ap-northeast-1.amazonaws.com/2022-05-28/1653713564-665112-3aa06a678e8679f3.png\"></p>\n<h3 id=\"5-第三次测试\"><a href=\"#5-第三次测试\" class=\"headerlink\" title=\"5.第三次测试\"></a>5.第三次测试</h3><p>一切顺利，这时候我们再输入正确的指令来试试抓取报错<br><img src=\"https://dice-forum.s3.ap-northeast-1.amazonaws.com/2022-05-28/1653713588-190887-7b41211a21a97483.png\"><br>因为这次输入了参数，即 <code>#basicFunction:tryCatch myDiary.txt</code>等效于 <code>#basicFunction:read_file myDiary.txt</code>，所以顺理成章的返回了里面的文本内容。</p>\n<h2 id=\"后记\"><a href=\"#后记\" class=\"headerlink\" title=\"后记\"></a>后记</h2><p>附上tryCatch函数的内容，如下:</p>\n<figure class=\"highlight lua\"><table><tr><td class=\"gutter\"><pre><span class=\"line\">1</span><br><span class=\"line\">2</span><br><span class=\"line\">3</span><br><span class=\"line\">4</span><br><span class=\"line\">5</span><br><span class=\"line\">6</span><br><span class=\"line\">7</span><br><span class=\"line\">8</span><br><span class=\"line\">9</span><br><span class=\"line\">10</span><br><span class=\"line\">11</span><br><span class=\"line\">12</span><br><span class=\"line\">13</span><br><span class=\"line\">14</span><br><span class=\"line\">15</span><br><span class=\"line\">16</span><br><span class=\"line\">17</span><br></pre></td><td class=\"code\"><pre><span class=\"line\"><span class=\"comment\">-----------------------------------------------------[15]:</span></span><br><span class=\"line\"><span class=\"comment\">-- 功能：监听错误报告如有则反馈</span></span><br><span class=\"line\"><span class=\"comment\">-- 参数：函数名</span></span><br><span class=\"line\"><span class=\"comment\">-- 返回：错误信息</span></span><br><span class=\"line\"><span class=\"comment\">-- 说明：lua有两个函数可以捕获异常，分别是pcall(fun[,arg1,...])和xpcall(fun,errfun,[,arg1,...])，对比这两个函数,xpcall多了异常处理，这里仅采用pcall()做示例</span></span><br><span class=\"line\">tryCatch = <span class=\"function\"><span class=\"keyword\">function</span><span class=\"params\">(fun,arg1,arg2,arg3,arg4,arg5)</span></span></span><br><span class=\"line\">  <span class=\"keyword\">local</span> ret,errMessage=<span class=\"built_in\">pcall</span>(fun,arg1,arg2,arg3,arg4,arg5);</span><br><span class=\"line\">  wrong=ret <span class=\"keyword\">and</span> <span class=\"string\">&quot;false&quot;</span> <span class=\"keyword\">or</span> <span class=\"string\">&quot;true&quot;</span></span><br><span class=\"line\">  <span class=\"comment\">--print(&quot;是否错误:\\n&quot;..错误..&quot; \\n\\n出错信息:\\n&quot; .. (errMessage or &quot;无&quot;));</span></span><br><span class=\"line\">  <span class=\"keyword\">if</span> wrong==<span class=\"string\">&quot;true&quot;</span> <span class=\"keyword\">then</span><span class=\"comment\">--错误提示</span></span><br><span class=\"line\">    <span class=\"keyword\">local</span> ret,errMessage=<span class=\"built_in\">pcall</span>(fun,arg1,arg2,arg3,arg4,arg5)</span><br><span class=\"line\">    <span class=\"keyword\">return</span> <span class=\"string\">&quot;\\n错误详情：\\n&quot;</span>..errMessage</span><br><span class=\"line\">  <span class=\"keyword\">else</span><span class=\"comment\">--无错误正常执行</span></span><br><span class=\"line\">    ret,back=<span class=\"built_in\">pcall</span>(fun,arg1,arg2,arg3,arg4,arg5);</span><br><span class=\"line\">    <span class=\"keyword\">return</span> <span class=\"string\">&quot;没有错误发生，返回值如下:\\n&quot;</span>..back</span><br><span class=\"line\">  <span class=\"keyword\">end</span></span><br><span class=\"line\"><span class=\"keyword\">end</span></span><br></pre></td></tr></table></figure>","_path":"2022/06/23/unlimited-errors/","_link":"https://hsiang-nianian.netlify.app/2022/06/23/unlimited-errors/","_id":"clanavjgk001aadoq7qlqaw1z"}}